name: Feature request
description:  Sugegst an idea for this project
title: '[New feature]:'
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? 
      description: A clear and concise description of what the problem is.
      placeholder: 'Example: I am trying to do [...] but [...]'
    validations:
      required: false
  - type: textarea
    attributes: 
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes: 
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false