__all__ = ["DocPipeline"]

from typing import Dict, List, Optional, Tuple, Union, cast

from medkit.core.annotation import Annotation
from medkit.core.document import Collection, Document
from medkit.core.operation import DocOperation
from medkit.core.pipeline import Pipeline
from medkit.core.prov_builder import ProvBuilder


class DocPipeline(DocOperation):
    """Wrapper around the `Pipeline` class that applies a list of a document or a`collection
    of documents

    Existing annotations, that are not generated by an operation in the pipeline
    but rather that should be retrieved from documents, can be handled by associating
    an annotation label to an input key. Pipeline steps using this input key will then
    receive as input all the existing document annotations having the associated label..
    """

    def __init__(
        self,
        pipeline: Pipeline,
        labels_by_input_key: Dict[str, List[str]],
        op_id: Optional[str] = None,
    ):
        """Initialize the pipeline

        Parameters
        ----------
        pipeline:
            Pipeline to execute on documents.
            `output_keys` in pipeline is used for selecting annotations to be
            added to documents
        labels_by_input_key:
            Mapping of input key to document annotation labels.

            This is a way to feed into the pipeline annotations
            that are not the result of a pipeline step, but that
            are pre-attached to the document on which the pipeline
            is running.

            For all pipeline step using `key` as an input key,
            the annotations of the document having the label `label`
            will be used as input.

            It is possible to associate several labels to one key,
            as well as to associate a label to several keys


        """
        # Pass all arguments to super (remove self)
        init_args = locals()
        init_args.pop("self")
        super().__init__(**init_args)

        self.pipeline = pipeline
        self.labels_by_input_key: Dict[str, List[str]] = labels_by_input_key

    def set_prov_builder(self, prov_builder: ProvBuilder):
        self.pipeline.set_prov_builder(prov_builder)

    def run(self, docs: Union[List[Document], Collection]) -> None:
        """Run the pipeline on a list of documents, adding
        the output annotations to each document

        Parameters
        ----------
        docs:
            The documents on which to run the pipeline.
            Labels to input keys association will be used to retrieve existing
            annotations from each document, and all output annotations will also
            be added to each corresponding document.
        """

        if isinstance(docs, Collection):
            docs = [doc for doc in docs.documents]

        for doc in docs:
            self._process_doc(doc)

    def _process_doc(self, doc: Document):
        all_input_anns = {}
        for input_key, labels in self.labels_by_input_key.items():
            for label in labels:
                if input_key not in all_input_anns:
                    all_input_anns[input_key] = doc.get_annotations_by_label(label)
                else:
                    all_input_anns[input_key] += doc.get_annotations_by_label(label)

        all_output_anns = self.pipeline.run(*all_input_anns.values())

        # wrap output in tuple if necessary
        # (operations performing in-place modifications
        # have no output and return None,
        # operations with single output may return a
        # single list instead of a tuple of lists)
        if all_output_anns is None:
            all_output_anns = tuple()
        elif not isinstance(all_output_anns, tuple):
            all_output_anns = (all_output_anns,)

        # operations must return annotations
        all_output_anns = cast(Tuple[List[Annotation], ...], all_output_anns)

        # add output anns to doc
        for output_anns in all_output_anns:
            for output_ann in output_anns:
                doc.add_annotation(output_ann)
