from __future__ import annotations

__all__ = ["TextDocument"]

import dataclasses
import random
from typing import Any, ClassVar, Dict, List, Optional
import uuid

from medkit.core.id import generate_id
from medkit.core.text.annotation import TextAnnotation, Segment, Entity, Relation
from medkit.core.text.annotation_container import TextAnnotationContainer
from medkit.core.text.span import Span


@dataclasses.dataclass(init=False)
class TextDocument:
    """
    Document holding text annotations

    Annotations must be subclasses of `TextAnnotation`.

    Attributes
    ----------
    uid:
        Unique identifier of the document.
    text:
        Full document text.
    anns:
        Annotations of the document. Stored in an
        :class:`~.TextAnnotationContainer` but can be passed as a list at init.
    metadata:
        Document metadata.
    raw_segment:
        Auto-generated segment containing the full unprocessed document text. To
        get the raw text as an annotation to pass to processing operations:

        >>> doc = TextDocument(text="hello")
        >>> raw_text = doc.anns.get(label=TextDocument.RAW_LABEL)[0]
    """

    RAW_LABEL: ClassVar[str] = "RAW_TEXT"

    uid: str
    anns: TextAnnotationContainer
    metadata: Dict[str, Any]
    raw_segment: Segment

    def __init__(
        self,
        text: str,
        anns: Optional[List[TextAnnotation]] = None,
        metadata: Optional[Dict[str, Any]] = None,
        uid: Optional[str] = None,
    ):
        if anns is None:
            anns = []
        if metadata is None:
            metadata = {}
        if uid is None:
            uid = generate_id()

        self.uid = uid
        self.metadata = metadata

        # auto-generated raw segment to hold the text
        self.raw_segment = self._generate_raw_segment(text, uid)

        self.anns = TextAnnotationContainer(
            doc_id=self.uid, raw_segment=self.raw_segment
        )
        for ann in anns:
            self.anns.add(ann)

    @classmethod
    def _generate_raw_segment(cls, text: str, doc_id: str) -> Segment:
        # generate deterministic uuid based on document uid
        # so that the annotation uid is the same if the doc uid is the same
        rng = random.Random(doc_id)
        uid = str(uuid.UUID(int=rng.getrandbits(128)))

        return Segment(
            label=cls.RAW_LABEL,
            spans=[Span(0, len(text))],
            text=text,
            uid=uid,
        )

    @property
    def text(self) -> str:
        return self.raw_segment.text

    def to_dict(self) -> Dict[str, Any]:
        anns = [ann.to_dict() for ann in self.anns]
        return dict(
            uid=self.uid,
            text=self.text,
            anns=anns,
            metadata=self.metadata,
            class_name=self.__class__.__name__,
        )

    @classmethod
    def from_dict(cls, doc_dict: Dict[str, Any]) -> TextDocument:
        """
        Creates a TextDocument from a dict

        Parameters
        ----------
        doc_dict: dict
            A dictionary from a serialized TextDocument as generated by to_dict()
        """
        anns = []
        for annotation_dict in doc_dict["anns"]:
            if annotation_dict["class_name"] == "Relation":
                anns.append(Relation.from_dict(annotation_dict))
            elif annotation_dict["class_name"] == "Segment":
                anns.append(Segment.from_dict(annotation_dict))
            elif annotation_dict["class_name"] == "Entity":
                anns.append(Entity.from_dict(annotation_dict))

        return cls(
            uid=doc_dict["uid"],
            text=doc_dict["text"],
            anns=anns,
            metadata=doc_dict["metadata"],
        )
